trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  backendPath: 'src'
  imageName: 'petpal-backend'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Backend Image
    jobs:
      - job: BuildImage
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              Dockerfile: 'Dockerfile'
              tags: |
                $(imageName):$(tag)
              buildContext: '.'

  - stage: Test
    displayName: Run Unit Tests
    condition: succeeded()
    jobs:
      - job: RunTests
        steps:
          - script: |
              echo "🔍 Acá se correrían los tests con Jest/Mocha"
              # npm install
              # npm test
            displayName: Placeholder Test Stage

  - stage: DeployQA
    condition: succeeded()
    jobs:
      - job: QADeploy
        steps:
          - script: echo "🚀 Aquí va el despliegue automático a QA (cuando esté configurado en Azure)"
            displayName: QA Deploy Placeholder

  - stage: DeployProd
    dependsOn: DeployQA
    condition: succeeded()
    jobs:
      - job: DeployToProduction
        steps:
          - script: echo "✅ Despliegue manual a Producción (Railway ya está configurado por push a main)"
            displayName: Manual Approval Placeholder
