name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3

    steps:
      - name: 🔄 Checkout repositorio
        uses: actions/checkout@v3

      - name: 📦 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Instalar dependencias
        run: npm install --no-bin-links

      - name: 🔧 Permisos a Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: 🔧 Esperar MySQL listo
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..." && sleep 3
          done

      - name: 🛠️ Crear .env
        run: |
          cat <<EOF > .env
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF

      - name: 🔄 Seedear la DB
        run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql

      - name: 🧪 Tests Unitarios
        run: npm run test:unit

      - name: 📊 Cobertura
        run: npm run coverage

      - name: 🧪 Tests Integración
        run: npm run test:integration


  deploy-qa:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v3

      - name: 🌱 Deploy “QA” en Railway (usa env production)
        run: |
          # Railway CLI lee RAILWAY_TOKEN del entorno
          npx @railway/cli up . \
            --environment production \
            --detach


  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v3

      - name: ✅ Esperar aprobación manual
        uses: peter-evans/wait-for-approval@v1
        with:
          reviewers: nicolasbergami,santiaguero7

      - name: 🟢 Deploy a Producción en Railway
        run: |
          npx @railway/cli up . \
            --environment production \
            --detach
