name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install --no-bin-links
      - run: chmod +x ./node_modules/.bin/jest
      - name: Esperar MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            sleep 3
          done
      - name: Crear .env
        run: |
          cat > .env <<EOF
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF
      - run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql
      - run: npm run test:unit
      - run: npm run coverage
      - run: npm run test:integration

  # RENOMBRADO A "ready-for-qa-approval"
  # Este job SÓLO verifica que la build pasó las pruebas y está lista.
  # NO despliega a Railway en este punto.
  ready-for-qa-approval:
    needs: build-and-test # Depende de que las pruebas y la construcción sean exitosas
    runs-on: ubuntu-latest
    steps:
      - name: El código ha pasado las pruebas y está listo para revisión de QA.
        run: echo "El código ha pasado las pruebas unitarias/integración y está listo para revisión/aprobación manual antes del despliegue a producción."
      # No hay ningún comando 'railway up' aquí.

  deploy-prod:
    needs: ready-for-qa-approval # Ahora este job depende del paso de "QA" (la preparación)
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app
    steps:
      - uses: actions/checkout@v3
      - name: Esperar aprobación manual para despliegue a PRODUCCIÓN
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: nicolasbergami,santiaguero7
          minimum-approvals: 1
          issue-title: "Aprobación manual requerida para deploy a producción"
      - name: Desplegar en Railway (PRODUCCIÓN REAL)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # ¡Este es el ÚNICO punto donde se realizará un despliegue a Railway!
          # Se especifica el servicio y el entorno directamente en el comando 'up',
          # ya que la CLI lo requiere explícitamente cuando hay múltiples servicios.
          npx @railway/cli@latest up . --service petpal-backend --environment production --detach