name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
        name: 🔄 Checkout repositorio

      - uses: actions/setup-node@v3
        name: 📦 Configurar Node.js
        with:
          node-version: 18

      - run: npm install --no-bin-links
        name: 📥 Instalar dependencias

      - run: chmod +x ./node_modules/.bin/jest
        name: 🔧 Dar permisos a Jest

      - run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..." && sleep 3
          done
        name: 🔧 Esperar MySQL listo

      - run: |
          cat <<EOF > .env
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF
        name: 🛠️ Crear archivo .env

      - run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql
        name: 🔄 Seedear la DB

      - run: npm run test:unit
        name: 🧪 Ejecutar Tests Unitarios

      - run: npm run coverage
        name: 📊 Generar Cobertura

      - run: npm run test:integration
        name: 🧪 Ejecutar Tests de Integración

  deploy-qa:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🔄 Checkout

      - run: |
          npm install -g @railway/cli
          railway login --apiKey $RAILWAY_TOKEN
          railway up . --environment production --detach
        name: 🚀 Deploy a QA
        # Nota: si quieres un QA separado crea otra env en Railway y cámbiala.

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app

    steps:
      - uses: actions/checkout@v3
        name: 🔄 Checkout

      - run: |
          npm install -g @railway/cli
          railway login --apiKey $RAILWAY_TOKEN
          railway up . --detach
        name: 🟢 Deploy a Producción
