name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install --no-bin-links
      - run: chmod +x ./node_modules/.bin/jest
      - name: Esperar MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            sleep 3
          done
      - name: Crear .env
        run: |
          cat > .env <<EOF
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF
      - run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql
      - run: npm run test:unit
      - run: npm run coverage
      - run: npm run test:integration

  ready-for-qa-approval:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: El código ha pasado las pruebas y está listo para revisión de QA.
        run: echo "El código ha pasado las pruebas unitarias/integración y está listo para revisión/aprobación manual antes del despliegue a producción."

  deploy-prod:
    needs: ready-for-qa-approval
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Esperar aprobación manual para despliegue a PRODUCCIÓN
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: nicolasbergami,santiaguero7
          minimum-approvals: 1
          issue-title: "Aprobación manual requerida para deploy a producción"
      
      # --- PASO DE DEPURACIÓN ÚNICO ---
      - name: Ejecutar comandos de depuración
        run: |
          echo "--- Debug: Listar archivos en el directorio actual ---"
          ls -la
          pwd
          echo "" # Línea en blanco para claridad

          echo "--- Debug: Contenido de railway.json ---"
          cat railway.json || echo "railway.json no encontrado o error de lectura"
          echo ""

          echo "--- Debug: Verificar variables de entorno de Railway ---"
          echo "Debug: RAILWAY_TOKEN raw access: ${{ secrets.RAILWAY_TOKEN }}"
          echo "Debug: RAILWAY_PROJECT_ID raw access: ${{ secrets.RAILWAY_PROJECT_ID }}"
          echo "RAILWAY_TOKEN_SET: ${{ contains(env.RAILWAY_TOKEN, '***') }}"
          echo "RAILWAY_PROJECT_SET: ${{ contains(env.RAILWAY_PROJECT_ID, 'b1639e5d') }}" 
          echo "RAILWAY_SERVICE_PASSED: petpal-backend"
          echo "RAILWAY_ENVIRONMENT_PASSED: production"
          echo ""
      # --- FIN DE PASO DE DEPURACIÓN ÚNICO ---

      - name: Desplegar en Railway (PRODUCCIÓN REAL)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          npx @railway/cli@latest up . --service petpal-backend --environment production --detach