name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --no-bin-links
      - run: chmod +x ./node_modules/.bin/jest
      - run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            sleep 3
          done
      - run: |
          cat <<EOF > .env
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF
      - run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql
      - run: npm run test:unit
      - run: npm run coverage
      - run: npm run test:integration

  deploy-qa:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to QA
        run: npx @railway/cli up . --environment qa --detach

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app
    steps:
      - uses: actions/checkout@v3
      - name: Wait for approval
        uses: peter-evans/wait-for-approval@v2
        with:
          reviewers: nicolasbergami,santiaguero7
      - name: Deploy to Production
        run: npx @railway/cli up . --environment production --detach
