name: Petpal CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-retries=3

    steps:
      - name: 🔄 Checkout repositorio
        uses: actions/checkout@v3

      - name: 📦 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Instalar dependencias
        run: npm install --no-bin-links

      - name: 🔧 Dar permisos a Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: 🔧 Esperar MySQL listo
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..." && sleep 3
          done

      - name: 🛠️ Crear archivo .env
        run: |
          cat <<EOF > .env
          DB_HOST=127.0.0.1
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=testdb
          DB_PORT=3306
          JWT_SECRET=testing-secret
          EOF

      - name: 🔄 Seedear la DB
        run: mysql -h127.0.0.1 -uroot -proot testdb < scripts/seed-ci.sql

      - name: 🧪 Ejecutar Tests Unitarios
        run: npm run test:unit

      - name: 📊 Generar Cobertura
        run: npm run coverage

      - name: 🧪 Ejecutar Tests de Integración
        run: npm run test:integration

  deploy-qa:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy a QA
        run: echo "Aquí harías el push a Railway QA..."

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest

    # Indica que este job despliega al entorno protegido "production"
    environment:
      name: production
      url: https://petpal-backend-production.up.railway.app

    steps:
      - name: ✅ Esperar aprobación
        run: echo "Esperando aprobación manual para producción…"

      - name: 🟢 Deploy a Producción
        run: echo "Railway hará el deploy automáticamente tras la aprobación"
